### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import random

vector = np.random.rand(10)
matrix = np.random.randint(0, 100, (3, 3))
vector, matrix
print(f"Вектор:\n{vector}\nЙого розмір: {vector.shape}")
print(f"Матриця:\n{matrix}\nЇї розмір: {matrix.shape}")  

Вектор:
[0.06935603 0.28106005 0.20467178 0.89131644 0.87778398 0.50651706
 0.45591924 0.36475425 0.28754684 0.79397111]
Його розмір: (10,)
Матриця:
[[98 80 13]
 [57 54  5]
 [15 42 39]]
Її розмір: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector = np.round(vector + 10, 2)
vector

array([10.07, 10.28, 10.2 , 10.89, 10.88, 10.51, 10.46, 10.36, 10.29,
       10.79])

In [3]:
matrix = matrix * 2
matrix

array([[196, 160,  26],
       [114, 108,  10],
       [ 30,  84,  78]])

In [4]:
vector_new = vector ** 2
vector_new

array([101.4049, 105.6784, 104.04  , 118.5921, 118.3744, 110.4601,
       109.4116, 107.3296, 105.8841, 116.4241])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [6]:
#1 щоб вийшла 2х2 - потрібно 2х3 домножити на 3х2
result_matrix = np.dot(B, A)
display(result_matrix)

# 2x2 помножити на 2х1 -> має вийти 2х1
result2x1 = np.dot(result_matrix, C)
display(result2x1)

# 2x2 помножити на 2х2 -> має вийти 2х2
result2x2 = np.dot(result_matrix, D)
display(result2x2)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.5202],
       [0.2846]])

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [7]:
result_matrix = result_matrix.T
result_matrix

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [8]:
vector = vector.T
vector
# змін немає, вектор залишився тієї ж розмірності
# але якби я його початково створила як матрицю (vector = np.random.rand(1, 10), то все би вдалось

array([10.07, 10.28, 10.2 , 10.89, 10.88, 10.51, 10.46, 10.36, 10.29,
       10.79])

In [9]:
column_vector = np.expand_dims(vector, axis=1)
column_vector
# так все працює, тепер зі стовпця ми отримали рядок

array([[10.07],
       [10.28],
       [10.2 ],
       [10.89],
       [10.88],
       [10.51],
       [10.46],
       [10.36],
       [10.29],
       [10.79]])

In [10]:
column_vector_T = column_vector.T
display(column_vector_T, column_vector_T.shape)
# отримали матрицю 1х10

array([[10.07, 10.28, 10.2 , 10.89, 10.88, 10.51, 10.46, 10.36, 10.29,
        10.79]])

(1, 10)